#!/bin/bash

#echo -n "Entre com o comando: "
#read VALOR

if [ -z "$1" ]; then
	echo "Por favor, digite um parâmetro no primeiro argumento"
	exit 1
fi

if [ -z "$2" ]; then
	echo "Por favor, digite um parâmetro no segundo argumento"
	exit 1
fi

echo "Nome do programa: $0"
echo "Primeiro argumento: $1"
echo "Segundo argumento: $2"

VALOR=$1

case "$VALOR" in
  start)
    echo "Foi digitado o comando start";;
  
  stop)
    echo "Foi digitado o comando stop";;

  *)
    echo "Por favor, digite APENAS start ou stop"
    exit 1;;
esac
echo "Fim do programa"
exit 0
