#!/bin/bash
# Este programa é um teste de função no shell

lista_diretorio(){
	ls $1 
	echo "A listagem do diretório $diretorio foi executada"
}

. biblioteca_funcoes

for diretorio in $1 $2 $3 $4 $5 $6 $7 $8 $9; do
#lista_diretorio $diretorio
  funcao1 $diretorio
#  funcao2 $diretorio  
done

# teste_funcao /bin /sbin /usr /tmp
